// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs defs_cosmo.go

package runtime

const (
	EINTR	= 0x4
	EFAULT	= 0xe
	_EAGAIN	= 0x23
	_ENOMEM	= 0xc

	_O_WRONLY	= 0x1
	O_NONBLOCK	= 0x4
	_O_CREAT	= 0x200
	_O_TRUNC	= 0x400
	O_CLOEXEC	= 0x80000

	_PROT_NONE	= 0x0
	_PROT_READ	= 0x1
	_PROT_WRITE	= 0x2
	_PROT_EXEC	= 0x4

	_MAP_ANON	= 0x20
	_MAP_PRIVATE	= 0x2
	_MAP_FIXED	= 0x10

	_MADV_DONTNEED		= 0x4
	_MADV_FREE		= 0x8
	_MADV_HUGEPAGE		= 0xe
	_MADV_NOHUGEPAGE	= 0xf
	_MADV_COLLAPSE		= 0x19

	_SA_SIGINFO	= 0x4
	_SA_RESTART	= 0x10000000
	_SA_ONSTACK	= 0x8000000

	_SI_USER	= 0

	_SIGHUP		= 0x1
	_SIGINT		= 0x2
	_SIGQUIT	= 0x3
	_SIGILL		= 0x4
	_SIGTRAP	= 0x5
	_SIGABRT	= 0x6

	_SIGFPE		= 0x8
	_SIGKILL	= 0x9

	_SIGSEGV	= 0xb

	_SIGPIPE	= 0xd
	_SIGALRM	= 0xe
	_SIGTERM	= 0xf
	_SIGURG		= 0x17

	_SIGTTIN	= 0x15
	_SIGTTOU	= 0x16

	_SIGXCPU	= 0x18
	_SIGXFSZ	= 0x19
	_SIGVTALRM	= 0x1a
	_SIGPROF	= 0x1b
	_SIGWINCH	= 0x1c

	BUS_ADRALN	= 0x1
	BUS_ADRERR	= 0x2
	BUS_OBJERR	= 0x3

	SEGV_MAPERR	= 0x1
	SEGV_ACCERR	= 0x2

	ITIMER_REAL	= 0x0
	ITIMER_VIRTUAL	= 0x1
	ITIMER_PROF	= 0x2

	_NSIG	= 0x80

	_FUTEX_WAIT		= 0
	_FUTEX_WAKE		= 1
	_FUTEX_PRIVATE_FLAG	= 128
	_FUTEX_WAIT_PRIVATE	= (_FUTEX_WAIT | _FUTEX_PRIVATE_FLAG)
	_FUTEX_WAKE_PRIVATE	= (_FUTEX_WAKE | _FUTEX_PRIVATE_FLAG)
)

type sigset struct {
	X__bits [2]uint64
}
type siginfo struct {
	Signo		int32
	Errno		int32
	Code		int32
	Pad_cgo_0	[4]byte
	Anon0		[112]byte
}
type sigactiont struct {
	Handler		*[0]byte
	Flags		uint64
	Restorer	*[0]byte
	Mask		sigset
}
type stackt struct {
	Sp	*byte
	Flags	int32
	Size	uint64
}

type timespec struct {
	Sec	int64
	Nsec	int64
}
type timeval struct {
	Sec	int64
	Usec	int64
}
type itimerval struct {
	Interval	timeval
	Value		timeval
}

type sigcontext struct{}
